### ISSUE TITLE
detector.py

### ISSUE THREAD

**Issue by richfubo** [wanyuac/screen_genes_in_assemblies#1]
Traceback (most recent call last):
  File "detector.py", line 836, in <module>
    main()
  File "detector.py", line 124, in main
    unique_allele_symbols = determine_allele_symbol_uniqueness(args.gene_db)  # return True of False
  File "detector.py", line 716, in determine_allele_symbol_uniqueness
    allele_name = name_parts[2]

HI
   I'm very interested in the software you and your team is working on.The following error occurred while I was running the detector.I'm new to bioinformatics, could you please help me solve this problem？

**Comment by wanyuac** [comment]
Hi, is there any other error message from Python interpreter? The traceback information pasted above is not adequate for troubleshooting. Thanks.
